### ISSUE TITLE
Potential resource leak not closing file

### ISSUE THREAD

**Issue by dreammaker** [Voxel8/OctoPrint-FirmwareUpdate#4]
See [this line](https://github.com/Voxel8/OctoPrint-FirmwareUpdate/blob/be3eb8ec83c9945ec314140402a0f3d73b0453dd/octoprint_firmwareupdate/__init__.py#L115) that opens a file.  There is no corresponding `close()` that I can see.  I'm very not familiar with `subprocess.Popen`, but from what I can tell, it doesn't close the file.  This could cause problems for any long-running process like OctoPrint.

**Comment by weedgrease** [comment]
Addressed/fixed in #6
